services:
  - type: web
    name: traffic-accident-data-monitor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_DEBUG
        value: "0"
